# Generated by Django 4.1.3 on 2022-11-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("hourlyRate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="WorkArrangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamLeader",
            fields=[
                (
                    "employee_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cmanager.employee",
                    ),
                ),
            ],
            bases=("cmanager.employee",),
        ),
        migrations.CreateModel(
            name="TeamEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employeeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cmanager.employee",
                    ),
                ),
                (
                    "teamId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cmanager.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="workArrangement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cmanager.workarrangement",
            ),
        ),
    ]
