# Generated by Django 4.1.3 on 2022-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                through="cmanager.TeamEmployee", to="cmanager.employee"
            ),
        ),
    ]
